services:
  prover:
    image: public.ecr.aws/succinct-labs/spn-node:latest-cpu
    container_name: succinct-prover
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    command: >
      sh -c "sleep 5 && calibrate
             --usd-cost-per-hour 0.80 \
             --utilization-rate 0.5 \
             --profit-margin 0.1 \
             --prove-price 1.00 &&
             prove
             --rpc-url https://rpc.sepolia.succinct.xyz
             --throughput $${PGUS_PER_SECOND}
             --bid $${PROVE_PER_BPGU}
             --private-key $${PRIVATE_KEY}
             --prover $${PROVER_ADDRESS}"
    env_file:
      - .env
    restart: unless-stopped